### ISSUE TITLE
submit seer to packagist

### ISSUE THREAD

**Issue by samayo** [Omarito2412/Seer#2]
[packagist](https://packagist.org) is a php code repository website, for sharing and management of dependancies

**Comment by Omarito2412** [comment]
Done, It's now on Packagist, Thank you.
I'll also learn PHPUnit to create unit tests for it soon, Any recommended resources?

**Comment by samayo** [comment]
This will help you get started with PHPUnit 
https://www.youtube.com/watch?v=HpVVhsuBT5c

Watch the videos #2 upto 6 (I think) for a good and basic understanding

**Comment by samayo** [comment]
also check my latest update and see if the changes appeal to you. I lower cased file names, seer construct also implements type hints, and removed the constant for the seer path ... check it

**Comment by Omarito2412** [comment]
Thanks just checked your changes.
But don't you think it would be better to keep the instantiation of the XPath, Curl, Output inside the Seer class? 
I think this would make it easier and scalable in case more Core classes were introduced

**Comment by samayo** [comment]
nope. I'm on mobile so I can't write much but my example uses dependancy injection. instanciating classes inside other classes is generally a bad idea. but, you can keep yours for now. There is no major difference, it's all about writing S.O.L.I.D  application

**Comment by samayo** [comment]
also if you want you can post this in /r/php and we will talk more about it

**Comment by Omarito2412** [comment]
Alright thanks I don't really mind so I'll pull your solution, Also I'll post it to /r/php once I've implemented more of the functionality so it can be reviewed and also gain some publicity.

**Comment by samayo** [comment]
I was going to sugest creating an expermental branch, but you've pulled it already. Though, trust me ..it's better to introduce DI in your application When you get time, you can add tests and scrutinizer also... Let me know if you need help

**Comment by Omarito2412** [comment]
The whole thing is quite alien to me but I'm learning, Once I'm over my exams I'll give it enough time.
Thanks for all your help!

**Comment by samayo** [comment]
We've all been there once. :) if you need a little help, or a push on any of these topics or more let me know.
